name: Serega VRS (I don't want you to think like me I just want you to think)
markdown: kramdown
theme: minima
google_analytics: UA-NNNNNNNN-N
permalink: /blog/:year/:month/:day/:title
url: "https://seregavrs.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
